---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: frontend
      level: novice
  template:
    metadata:
      labels:
        app: frontend
        level: novice
    spec:
      containers:
        - name: nginx-fe
          image: nginx:stable-alpine
          ports:
            - containerPort: 80
