---
apiVersion: v1
kind: Pod
metadata:
  name: yaml-pod
  labels:
    run: yaml-pod
spec:
  containers:
    - name: yaml-pod
      image: containous/whoami:latest
      ports:
        - containerPort: 80
